# Generated by Django 4.2 on 2023-04-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20, max_length=50)),
                ('description', models.TextField(default='The real stallion 💪')),
                ('height', models.FloatField(default=180)),
                ('weight', models.FloatField(default=70)),
                ('is_virgin', models.BooleanField(default=False)),
                ('price', models.FloatField(default=1000)),
            ],
        ),
    ]
