# Generated by Django 4.2 on 2023-04-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
