# Generated by Django 4.2.2 on 2023-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_packageprice_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='basicservice',
            name='title',
        ),
        migrations.RemoveField(
            model_name='extreme',
            name='title',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='sadomazo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='striptease',
            name='title',
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='cum_in_mouth',
            field=models.BooleanField(blank=True, default=False, verbose_name='Кончить в рот'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='cum_on_face',
            field=models.BooleanField(blank=True, default=False, verbose_name='Кончить на лицо'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='deep_blowjob',
            field=models.BooleanField(blank=True, default=False, verbose_name='Глубокий минет'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='escort',
            field=models.BooleanField(blank=True, default=False, verbose_name='Сопровождение'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='photo_video_shooting',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фото/видео съемка'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='role_playing_games',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ролевые игры'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='services_for_couples',
            field=models.BooleanField(blank=True, default=False, verbose_name='Услуги семейной паре'),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='toys',
            field=models.BooleanField(blank=True, default=False, verbose_name='Игрушки'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='anal_sex',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, verbose_name='Анальный секс'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='blowjob_without_condom',
            field=models.CharField(blank=True, choices=[('Yes', 'Да'), ('No', 'Нет')], max_length=10, verbose_name='Минет без презерватива'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='classic_sex',
            field=models.BooleanField(blank=True, default=False, verbose_name='Классический секс'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='condom_blowjob',
            field=models.BooleanField(blank=True, default=False, verbose_name='Минет с презервативом'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='cunnilingus',
            field=models.BooleanField(blank=True, default=False, verbose_name='Кунилингус'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='group_sex',
            field=models.BooleanField(blank=True, default=False, verbose_name='Групповой секс'),
        ),
        migrations.AddField(
            model_name='basicservice',
            name='lesbian_sex',
            field=models.BooleanField(blank=True, default=False, verbose_name='Лесбийский секс'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='anilingus',
            field=models.BooleanField(blank=True, default=False, verbose_name='Анилингус'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='fisting_anal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фистинг анальный'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='fisting_vaginal',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фистинг вагинальный'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='golden_rain_issuance',
            field=models.BooleanField(blank=True, default=False, verbose_name='Золотой дождь выдача'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='golden_rain_reception',
            field=models.BooleanField(blank=True, default=False, verbose_name='Золотой дождь прием'),
        ),
        migrations.AddField(
            model_name='extreme',
            name='strapon',
            field=models.BooleanField(blank=True, default=False, verbose_name='Страпон'),
        ),
        migrations.AddField(
            model_name='massage',
            name='classic_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Классический массаж'),
        ),
        migrations.AddField(
            model_name='massage',
            name='erotic_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Эротический массаж'),
        ),
        migrations.AddField(
            model_name='massage',
            name='pro_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Профессиональный массаж'),
        ),
        migrations.AddField(
            model_name='massage',
            name='prostate_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Массаж простаты'),
        ),
        migrations.AddField(
            model_name='massage',
            name='relaxing_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Расслабляющий массаж'),
        ),
        migrations.AddField(
            model_name='massage',
            name='sakura_branch',
            field=models.BooleanField(blank=True, default=False, verbose_name='Ветка сакуры'),
        ),
        migrations.AddField(
            model_name='massage',
            name='thai_massage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Тайский массаж'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='bandage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бандаж'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='fetish',
            field=models.BooleanField(blank=True, default=False, verbose_name='Фетиш'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='flogging',
            field=models.BooleanField(blank=True, default=False, verbose_name='Порка'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='light_domination',
            field=models.BooleanField(blank=True, default=False, verbose_name='Легкая доминация'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='mistress',
            field=models.BooleanField(blank=True, default=False, verbose_name='Госпожа'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='slave',
            field=models.BooleanField(blank=True, default=False, verbose_name='Рабыня'),
        ),
        migrations.AddField(
            model_name='sadomazo',
            name='trampling',
            field=models.BooleanField(blank=True, default=False, verbose_name='Трамплинг'),
        ),
        migrations.AddField(
            model_name='striptease',
            name='candid_lesbian_show',
            field=models.BooleanField(blank=True, default=False, verbose_name='Откровенное лесби-шоу'),
        ),
        migrations.AddField(
            model_name='striptease',
            name='easy_lesbian_show',
            field=models.BooleanField(blank=True, default=False, verbose_name='Легкое лесби шоу'),
        ),
        migrations.AddField(
            model_name='striptease',
            name='striptease_not_pro',
            field=models.BooleanField(blank=True, default=False, verbose_name='Стриптиз не профи'),
        ),
        migrations.AddField(
            model_name='striptease',
            name='striptease_pro',
            field=models.BooleanField(blank=True, default=False, verbose_name='Стриптиз профи'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='apartments_1h',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Апартаменты 1 час'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='apartments_2h',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Апартаменты 2 часа'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='apartments_night',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Апартаменты ночь'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='departure_1h',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Выезд 1 час'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='departure_2h',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Выезд 2 часа'),
        ),
        migrations.AlterField(
            model_name='packageprice',
            name='departure_night',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Выезд ночь'),
        ),
    ]
