# Generated by Django 4.2.2 on 2023-07-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_basicservicebool_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicServiceBool',
        ),
    ]
