# Generated by Django 4.2.3 on 2023-07-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_delete_basicservicebool'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicservice',
            name='boolean',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Основная услуга'),
        ),
        migrations.AlterField(
            model_name='basicservice',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Основная услуга'),
        ),
    ]
