# Generated by Django 4.2.2 on 2023-07-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DidYouKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True, verbose_name='вопрос')),
                ('question', models.TextField(null=True, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'А знаете ли вы?',
                'verbose_name_plural': 'А знаете ли вы?',
            },
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, null=True, verbose_name='вопрос')),
                ('question', models.TextField(null=True, verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'Помощь',
                'verbose_name_plural': 'Помощь',
            },
        ),
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'Техподдержка', 'verbose_name_plural': 'Техподдержки'},
        ),
        migrations.RemoveField(
            model_name='miniblog',
            name='description',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='miniblog',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='miniblog',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='support',
            name='mail',
            field=models.EmailField(max_length=50, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=20, null=True, verbose_name='Тема'),
        ),
    ]
