# Generated by Django 4.2.2 on 2023-07-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_alter_minibloggallery_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(max_length=16, verbose_name='номер телефона')),
                ('phone_number_2', models.CharField(blank=True, max_length=16, verbose_name='номер телефона')),
                ('phone_number_3', models.CharField(blank=True, max_length=16, verbose_name='номер телефона')),
                ('social_media_1', models.URLField(verbose_name='соц сеть')),
                ('social_media_2', models.URLField(blank=True, verbose_name='соц сеть')),
                ('social_media_3', models.URLField(blank=True, verbose_name='соц сеть')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
            },
        ),
        migrations.AlterModelOptions(
            name='minibloggallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterField(
            model_name='minibloggallery',
            name='mini_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='others.miniblog'),
        ),
        migrations.AlterField(
            model_name='support',
            name='mail',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='support',
            name='subject',
            field=models.CharField(max_length=100, null=True, verbose_name='Тема'),
        ),
    ]
