# Generated by Django 4.2 on 2023-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='additional_service',
            field=models.ManyToManyField(blank=True, null=True, to='services.additionalservice'),
        ),
        migrations.AlterField(
            model_name='model',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='extreme',
            field=models.ManyToManyField(blank=True, null=True, to='services.extreme'),
        ),
        migrations.AlterField(
            model_name='model',
            name='massage',
            field=models.ManyToManyField(blank=True, null=True, to='services.massage'),
        ),
        migrations.AlterField(
            model_name='model',
            name='sadomazo',
            field=models.ManyToManyField(blank=True, null=True, to='services.sadomazo'),
        ),
        migrations.AlterField(
            model_name='model',
            name='striptease',
            field=models.ManyToManyField(blank=True, null=True, to='services.striptease'),
        ),
    ]
