# Generated by Django 4.2 on 2023-06-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_model_additional_service_alter_model_extreme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='model_photos')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='models.model')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
    ]
