# Generated by Django 4.2 on 2023-06-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_modelsgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='photo',
        ),
    ]
