# Generated by Django 4.2.2 on 2023-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_basicservicebool_and_more'),
        ('models', '0007_remove_model_additional_service_alter_model_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='additional_service',
        ),
        migrations.RemoveField(
            model_name='model',
            name='basic_service',
        ),
        migrations.RemoveField(
            model_name='model',
            name='extreme',
        ),
        migrations.RemoveField(
            model_name='model',
            name='massage',
        ),
        migrations.RemoveField(
            model_name='model',
            name='sadomazo',
        ),
        migrations.RemoveField(
            model_name='model',
            name='striptease',
        ),
        migrations.AddField(
            model_name='model',
            name='additional_service',
            field=models.ManyToManyField(blank=True, related_name='model', to='services.additionalservice', verbose_name='Дополнительные услуги'),
        ),
        migrations.AddField(
            model_name='model',
            name='basic_service',
            field=models.ManyToManyField(related_name='model', to='services.basicservice', verbose_name='Основные услуги'),
        ),
        migrations.AddField(
            model_name='model',
            name='extreme',
            field=models.ManyToManyField(blank=True, related_name='model', to='services.extreme', verbose_name='Экстрим'),
        ),
        migrations.AddField(
            model_name='model',
            name='massage',
            field=models.ManyToManyField(blank=True, related_name='model', to='services.massage', verbose_name='Массаж'),
        ),
        migrations.AddField(
            model_name='model',
            name='sadomazo',
            field=models.ManyToManyField(blank=True, related_name='model', to='services.sadomazo', verbose_name='Садо-мазо'),
        ),
        migrations.AddField(
            model_name='model',
            name='striptease',
            field=models.ManyToManyField(blank=True, related_name='model', to='services.striptease', verbose_name='Стриптиз'),
        ),
    ]
