# Generated by Django 4.2.3 on 2023-07-19 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0012_model_photo_1_model_photo_2_model_photo_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
